version: '3'
services:
  my-app:
    container_name: my-app
    image: cosmtrek/air
    command: -c ./server.debug.toml
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8080:8080
      - 2345:2345